AddonId: 'HeliumWithTabs-8b15c46a-90c2-4fe5-9ebb-1ab25ba7fcb2'
Packages:
  - Version: 2.0
    RequiredApiVersion: 5.6.0
    ReleaseDate: 2024-02-03
    PackageUrl: https://github.com/tetj/HeliumWithTabs/releases/download/v3/HeliumWithTabs-8b15c46a-90c2-4fe5-9ebb-1ab25ba7fcb2_1_66.pthm
    Changelog:
      - First release
